## 服务端口
#server.port=8080
#
## jdbc
#spring.datasource.password=4321`qaz
#spring.datasource.username=gmail
#spring.datasource.url=jdbc:mysql://localhost:3306/gmail?characterEncoding=UTF-8
#
## mybtais配置
#mybatis.mapper-locations=classpath:mapper/*Mapper.xml
#mybatis.configuration.map-underscore-to-camel-case=true
#
## 日志级别
#logging.level.root=info
server:
  port: 8070
spring:
  datasource:
    druid:
      username: gmail
      password: 4321`qaz
      url: jdbc:mysql://localhost:3306/gmail?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  dubbo:
    application: user-service
    protocol:
      name: dubbo
    registry:
      address: 192.168.211.51:2181
      protocol: zookeeper
    base-package: com.ac.gmall

mybatis:
  type-aliases-package: entity
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    cache-enabled: true # 在本项目之中开启二级缓存
