package entity;

import java.io.Serializable;
import java.util.List;

public class PmsBaseAttrInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_attr_info.id
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_attr_info.attr_name
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    private String attrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_attr_info.catalog3_id
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    private Long catalog3Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_attr_info.is_enabled
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    private String isEnabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_base_attr_info
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_attr_info.id
     *
     * @return the value of pms_base_attr_info.id
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_attr_info.id
     *
     * @param id the value for pms_base_attr_info.id
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_attr_info.attr_name
     *
     * @return the value of pms_base_attr_info.attr_name
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    public String getAttrName() {
        return attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_attr_info.attr_name
     *
     * @param attrName the value for pms_base_attr_info.attr_name
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    public void setAttrName(String attrName) {
        this.attrName = attrName == null ? null : attrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_attr_info.catalog3_id
     *
     * @return the value of pms_base_attr_info.catalog3_id
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    public Long getCatalog3Id() {
        return catalog3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_attr_info.catalog3_id
     *
     * @param catalog3Id the value for pms_base_attr_info.catalog3_id
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    public void setCatalog3Id(Long catalog3Id) {
        this.catalog3Id = catalog3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_attr_info.is_enabled
     *
     * @return the value of pms_base_attr_info.is_enabled
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    public String getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_attr_info.is_enabled
     *
     * @param isEnabled the value for pms_base_attr_info.is_enabled
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    public void setIsEnabled(String isEnabled) {
        this.isEnabled = isEnabled == null ? null : isEnabled.trim();
    }

    public List<PmsBaseAttrValue> getAttrValueList() {
        return attrValueList;
    }

    public void setAttrValueList(List<PmsBaseAttrValue> attrValueList) {
        this.attrValueList = attrValueList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    List<PmsBaseAttrValue> attrValueList;
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", attrName=").append(attrName);
        sb.append(", catalog3Id=").append(catalog3Id);
        sb.append(", isEnabled=").append(isEnabled);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PmsBaseAttrInfo other = (PmsBaseAttrInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAttrName() == null ? other.getAttrName() == null : this.getAttrName().equals(other.getAttrName()))
            && (this.getCatalog3Id() == null ? other.getCatalog3Id() == null : this.getCatalog3Id().equals(other.getCatalog3Id()))
            && (this.getIsEnabled() == null ? other.getIsEnabled() == null : this.getIsEnabled().equals(other.getIsEnabled()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAttrName() == null) ? 0 : getAttrName().hashCode());
        result = prime * result + ((getCatalog3Id() == null) ? 0 : getCatalog3Id().hashCode());
        result = prime * result + ((getIsEnabled() == null) ? 0 : getIsEnabled().hashCode());
        return result;
    }
}