package entity;

import java.io.Serializable;

public class PmsBaseAttrValue implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_attr_value.id
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_attr_value.value_name
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    private String valueName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_attr_value.attr_id
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    private Long attrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_attr_value.is_enabled
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    private String isEnabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_base_attr_value
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_attr_value.id
     *
     * @return the value of pms_base_attr_value.id
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_attr_value.id
     *
     * @param id the value for pms_base_attr_value.id
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_attr_value.value_name
     *
     * @return the value of pms_base_attr_value.value_name
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    public String getValueName() {
        return valueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_attr_value.value_name
     *
     * @param valueName the value for pms_base_attr_value.value_name
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    public void setValueName(String valueName) {
        this.valueName = valueName == null ? null : valueName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_attr_value.attr_id
     *
     * @return the value of pms_base_attr_value.attr_id
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    public Long getAttrId() {
        return attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_attr_value.attr_id
     *
     * @param attrId the value for pms_base_attr_value.attr_id
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    public void setAttrId(Long attrId) {
        this.attrId = attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_attr_value.is_enabled
     *
     * @return the value of pms_base_attr_value.is_enabled
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    public String getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_attr_value.is_enabled
     *
     * @param isEnabled the value for pms_base_attr_value.is_enabled
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    public void setIsEnabled(String isEnabled) {
        this.isEnabled = isEnabled == null ? null : isEnabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_value
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", valueName=").append(valueName);
        sb.append(", attrId=").append(attrId);
        sb.append(", isEnabled=").append(isEnabled);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_value
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PmsBaseAttrValue other = (PmsBaseAttrValue) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getValueName() == null ? other.getValueName() == null : this.getValueName().equals(other.getValueName()))
            && (this.getAttrId() == null ? other.getAttrId() == null : this.getAttrId().equals(other.getAttrId()))
            && (this.getIsEnabled() == null ? other.getIsEnabled() == null : this.getIsEnabled().equals(other.getIsEnabled()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_value
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getValueName() == null) ? 0 : getValueName().hashCode());
        result = prime * result + ((getAttrId() == null) ? 0 : getAttrId().hashCode());
        result = prime * result + ((getIsEnabled() == null) ? 0 : getIsEnabled().hashCode());
        return result;
    }
}