package entity;

import java.io.Serializable;
import java.util.List;

public class PmsProductSaleAttr implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_sale_attr.id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_sale_attr.product_id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_sale_attr.sale_attr_id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    private Long saleAttrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_sale_attr.sale_attr_name
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    private String saleAttrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_product_sale_attr
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_sale_attr.id
     *
     * @return the value of pms_product_sale_attr.id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_sale_attr.id
     *
     * @param id the value for pms_product_sale_attr.id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_sale_attr.product_id
     *
     * @return the value of pms_product_sale_attr.product_id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_sale_attr.product_id
     *
     * @param productId the value for pms_product_sale_attr.product_id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_sale_attr.sale_attr_id
     *
     * @return the value of pms_product_sale_attr.sale_attr_id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public Long getSaleAttrId() {
        return saleAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_sale_attr.sale_attr_id
     *
     * @param saleAttrId the value for pms_product_sale_attr.sale_attr_id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public void setSaleAttrId(Long saleAttrId) {
        this.saleAttrId = saleAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_sale_attr.sale_attr_name
     *
     * @return the value of pms_product_sale_attr.sale_attr_name
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public String getSaleAttrName() {
        return saleAttrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_sale_attr.sale_attr_name
     *
     * @param saleAttrName the value for pms_product_sale_attr.sale_attr_name
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public void setSaleAttrName(String saleAttrName) {
        this.saleAttrName = saleAttrName == null ? null : saleAttrName.trim();
    }

    private List<PmsProductSaleAttrValue> spuSaleAttrValueList;

    public List<PmsProductSaleAttrValue> getSpuSaleAttrValueList() {
        return spuSaleAttrValueList;
    }

    public void setSpuSaleAttrValueList(List<PmsProductSaleAttrValue> spuSaleAttrValueList) {
        this.spuSaleAttrValueList = spuSaleAttrValueList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", saleAttrId=").append(saleAttrId);
        sb.append(", saleAttrName=").append(saleAttrName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PmsProductSaleAttr other = (PmsProductSaleAttr) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getSaleAttrId() == null ? other.getSaleAttrId() == null : this.getSaleAttrId().equals(other.getSaleAttrId()))
            && (this.getSaleAttrName() == null ? other.getSaleAttrName() == null : this.getSaleAttrName().equals(other.getSaleAttrName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getSaleAttrId() == null) ? 0 : getSaleAttrId().hashCode());
        result = prime * result + ((getSaleAttrName() == null) ? 0 : getSaleAttrName().hashCode());
        return result;
    }
}