package entity;

import java.beans.Transient;
import java.io.Serializable;
import java.util.List;

public class PmsProductInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_info.id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_info.product_name
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_info.description
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_info.catalog3_id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    private Long catalog3Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_info.tm_id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    private Long tmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_product_info
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_info.id
     *
     * @return the value of pms_product_info.id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_info.id
     *
     * @param id the value for pms_product_info.id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_info.product_name
     *
     * @return the value of pms_product_info.product_name
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_info.product_name
     *
     * @param productName the value for pms_product_info.product_name
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_info.description
     *
     * @return the value of pms_product_info.description
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_info.description
     *
     * @param description the value for pms_product_info.description
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_info.catalog3_id
     *
     * @return the value of pms_product_info.catalog3_id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public Long getCatalog3Id() {
        return catalog3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_info.catalog3_id
     *
     * @param catalog3Id the value for pms_product_info.catalog3_id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public void setCatalog3Id(Long catalog3Id) {
        this.catalog3Id = catalog3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_info.tm_id
     *
     * @return the value of pms_product_info.tm_id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public Long getTmId() {
        return tmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_info.tm_id
     *
     * @param tmId the value for pms_product_info.tm_id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public void setTmId(Long tmId) {
        this.tmId = tmId;
    }

    public List<PmsProductImage> getSpuImageList() {
        return spuImageList;
    }

    public void setSpuImageList(List<PmsProductImage> spuImageList) {
        this.spuImageList = spuImageList;
    }

    public List<PmsProductSaleAttr> getSpuSaleAttrList() {
        return spuSaleAttrList;
    }

    public void setSpuSaleAttrList(List<PmsProductSaleAttr> spuSaleAttrList) {
        this.spuSaleAttrList = spuSaleAttrList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    private List<PmsProductImage> spuImageList;
    private List<PmsProductSaleAttr> spuSaleAttrList;

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productName=").append(productName);
        sb.append(", description=").append(description);
        sb.append(", catalog3Id=").append(catalog3Id);
        sb.append(", tmId=").append(tmId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PmsProductInfo other = (PmsProductInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getProductName() == null ? other.getProductName() == null : this.getProductName().equals(other.getProductName()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getCatalog3Id() == null ? other.getCatalog3Id() == null : this.getCatalog3Id().equals(other.getCatalog3Id()))
            && (this.getTmId() == null ? other.getTmId() == null : this.getTmId().equals(other.getTmId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProductName() == null) ? 0 : getProductName().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getCatalog3Id() == null) ? 0 : getCatalog3Id().hashCode());
        result = prime * result + ((getTmId() == null) ? 0 : getTmId().hashCode());
        return result;
    }
}