package entity;

import java.io.Serializable;

public class PmsProductSaleAttrValue implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_sale_attr_value.id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_sale_attr_value.product_id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_sale_attr_value.sale_attr_id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    private Long saleAttrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_sale_attr_value.sale_attr_value_name
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    private String saleAttrValueName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_product_sale_attr_value
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_sale_attr_value.id
     *
     * @return the value of pms_product_sale_attr_value.id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_sale_attr_value.id
     *
     * @param id the value for pms_product_sale_attr_value.id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_sale_attr_value.product_id
     *
     * @return the value of pms_product_sale_attr_value.product_id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_sale_attr_value.product_id
     *
     * @param productId the value for pms_product_sale_attr_value.product_id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_sale_attr_value.sale_attr_id
     *
     * @return the value of pms_product_sale_attr_value.sale_attr_id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public Long getSaleAttrId() {
        return saleAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_sale_attr_value.sale_attr_id
     *
     * @param saleAttrId the value for pms_product_sale_attr_value.sale_attr_id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public void setSaleAttrId(Long saleAttrId) {
        this.saleAttrId = saleAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_sale_attr_value.sale_attr_value_name
     *
     * @return the value of pms_product_sale_attr_value.sale_attr_value_name
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public String getSaleAttrValueName() {
        return saleAttrValueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_sale_attr_value.sale_attr_value_name
     *
     * @param saleAttrValueName the value for pms_product_sale_attr_value.sale_attr_value_name
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public void setSaleAttrValueName(String saleAttrValueName) {
        this.saleAttrValueName = saleAttrValueName == null ? null : saleAttrValueName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr_value
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", saleAttrId=").append(saleAttrId);
        sb.append(", saleAttrValueName=").append(saleAttrValueName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr_value
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PmsProductSaleAttrValue other = (PmsProductSaleAttrValue) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getSaleAttrId() == null ? other.getSaleAttrId() == null : this.getSaleAttrId().equals(other.getSaleAttrId()))
            && (this.getSaleAttrValueName() == null ? other.getSaleAttrValueName() == null : this.getSaleAttrValueName().equals(other.getSaleAttrValueName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr_value
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getSaleAttrId() == null) ? 0 : getSaleAttrId().hashCode());
        result = prime * result + ((getSaleAttrValueName() == null) ? 0 : getSaleAttrValueName().hashCode());
        return result;
    }
}