package entity;

import java.io.Serializable;

public class PmsProductImage implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_image.id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_image.product_id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_image.img_name
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    private String imgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_image.img_url
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_product_image
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_image.id
     *
     * @return the value of pms_product_image.id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_image.id
     *
     * @param id the value for pms_product_image.id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_image.product_id
     *
     * @return the value of pms_product_image.product_id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_image.product_id
     *
     * @param productId the value for pms_product_image.product_id
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_image.img_name
     *
     * @return the value of pms_product_image.img_name
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public String getImgName() {
        return imgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_image.img_name
     *
     * @param imgName the value for pms_product_image.img_name
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public void setImgName(String imgName) {
        this.imgName = imgName == null ? null : imgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_image.img_url
     *
     * @return the value of pms_product_image.img_url
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_image.img_url
     *
     * @param imgUrl the value for pms_product_image.img_url
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_image
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", imgName=").append(imgName);
        sb.append(", imgUrl=").append(imgUrl);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_image
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PmsProductImage other = (PmsProductImage) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getImgName() == null ? other.getImgName() == null : this.getImgName().equals(other.getImgName()))
            && (this.getImgUrl() == null ? other.getImgUrl() == null : this.getImgUrl().equals(other.getImgUrl()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_image
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getImgName() == null) ? 0 : getImgName().hashCode());
        result = prime * result + ((getImgUrl() == null) ? 0 : getImgUrl().hashCode());
        return result;
    }
}