package entity;

import java.io.Serializable;
import java.util.Date;

public class UserMember implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member.id
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member.member_level_id
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    private Long memberLevelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member.username
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member.password
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member.nickname
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member.phone
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member.status
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member.create_time
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member.icon
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member.gender
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member.birthday
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member.city
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member.job
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member.personalized_signature
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    private String personalizedSignature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member.source_type
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    private Integer sourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member.integration
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    private Integer integration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member.growth
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    private Integer growth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member.luckey_count
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    private Integer luckeyCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member.history_integration
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    private Integer historyIntegration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_member
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member.id
     *
     * @return the value of ums_member.id
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member.id
     *
     * @param id the value for ums_member.id
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member.member_level_id
     *
     * @return the value of ums_member.member_level_id
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public Long getMemberLevelId() {
        return memberLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member.member_level_id
     *
     * @param memberLevelId the value for ums_member.member_level_id
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public void setMemberLevelId(Long memberLevelId) {
        this.memberLevelId = memberLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member.username
     *
     * @return the value of ums_member.username
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member.username
     *
     * @param username the value for ums_member.username
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member.password
     *
     * @return the value of ums_member.password
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member.password
     *
     * @param password the value for ums_member.password
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member.nickname
     *
     * @return the value of ums_member.nickname
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member.nickname
     *
     * @param nickname the value for ums_member.nickname
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member.phone
     *
     * @return the value of ums_member.phone
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member.phone
     *
     * @param phone the value for ums_member.phone
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member.status
     *
     * @return the value of ums_member.status
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member.status
     *
     * @param status the value for ums_member.status
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member.create_time
     *
     * @return the value of ums_member.create_time
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member.create_time
     *
     * @param createTime the value for ums_member.create_time
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member.icon
     *
     * @return the value of ums_member.icon
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member.icon
     *
     * @param icon the value for ums_member.icon
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member.gender
     *
     * @return the value of ums_member.gender
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member.gender
     *
     * @param gender the value for ums_member.gender
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member.birthday
     *
     * @return the value of ums_member.birthday
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member.birthday
     *
     * @param birthday the value for ums_member.birthday
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member.city
     *
     * @return the value of ums_member.city
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member.city
     *
     * @param city the value for ums_member.city
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member.job
     *
     * @return the value of ums_member.job
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member.job
     *
     * @param job the value for ums_member.job
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member.personalized_signature
     *
     * @return the value of ums_member.personalized_signature
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public String getPersonalizedSignature() {
        return personalizedSignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member.personalized_signature
     *
     * @param personalizedSignature the value for ums_member.personalized_signature
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public void setPersonalizedSignature(String personalizedSignature) {
        this.personalizedSignature = personalizedSignature == null ? null : personalizedSignature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member.source_type
     *
     * @return the value of ums_member.source_type
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public Integer getSourceType() {
        return sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member.source_type
     *
     * @param sourceType the value for ums_member.source_type
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public void setSourceType(Integer sourceType) {
        this.sourceType = sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member.integration
     *
     * @return the value of ums_member.integration
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public Integer getIntegration() {
        return integration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member.integration
     *
     * @param integration the value for ums_member.integration
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public void setIntegration(Integer integration) {
        this.integration = integration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member.growth
     *
     * @return the value of ums_member.growth
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public Integer getGrowth() {
        return growth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member.growth
     *
     * @param growth the value for ums_member.growth
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public void setGrowth(Integer growth) {
        this.growth = growth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member.luckey_count
     *
     * @return the value of ums_member.luckey_count
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public Integer getLuckeyCount() {
        return luckeyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member.luckey_count
     *
     * @param luckeyCount the value for ums_member.luckey_count
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public void setLuckeyCount(Integer luckeyCount) {
        this.luckeyCount = luckeyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member.history_integration
     *
     * @return the value of ums_member.history_integration
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public Integer getHistoryIntegration() {
        return historyIntegration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member.history_integration
     *
     * @param historyIntegration the value for ums_member.history_integration
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    public void setHistoryIntegration(Integer historyIntegration) {
        this.historyIntegration = historyIntegration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", memberLevelId=").append(memberLevelId);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", nickname=").append(nickname);
        sb.append(", phone=").append(phone);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", icon=").append(icon);
        sb.append(", gender=").append(gender);
        sb.append(", birthday=").append(birthday);
        sb.append(", city=").append(city);
        sb.append(", job=").append(job);
        sb.append(", personalizedSignature=").append(personalizedSignature);
        sb.append(", sourceType=").append(sourceType);
        sb.append(", integration=").append(integration);
        sb.append(", growth=").append(growth);
        sb.append(", luckeyCount=").append(luckeyCount);
        sb.append(", historyIntegration=").append(historyIntegration);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserMember other = (UserMember) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMemberLevelId() == null ? other.getMemberLevelId() == null : this.getMemberLevelId().equals(other.getMemberLevelId()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getNickname() == null ? other.getNickname() == null : this.getNickname().equals(other.getNickname()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getIcon() == null ? other.getIcon() == null : this.getIcon().equals(other.getIcon()))
            && (this.getGender() == null ? other.getGender() == null : this.getGender().equals(other.getGender()))
            && (this.getBirthday() == null ? other.getBirthday() == null : this.getBirthday().equals(other.getBirthday()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getJob() == null ? other.getJob() == null : this.getJob().equals(other.getJob()))
            && (this.getPersonalizedSignature() == null ? other.getPersonalizedSignature() == null : this.getPersonalizedSignature().equals(other.getPersonalizedSignature()))
            && (this.getSourceType() == null ? other.getSourceType() == null : this.getSourceType().equals(other.getSourceType()))
            && (this.getIntegration() == null ? other.getIntegration() == null : this.getIntegration().equals(other.getIntegration()))
            && (this.getGrowth() == null ? other.getGrowth() == null : this.getGrowth().equals(other.getGrowth()))
            && (this.getLuckeyCount() == null ? other.getLuckeyCount() == null : this.getLuckeyCount().equals(other.getLuckeyCount()))
            && (this.getHistoryIntegration() == null ? other.getHistoryIntegration() == null : this.getHistoryIntegration().equals(other.getHistoryIntegration()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     *
     * @mbggenerated Sun Nov 24 20:23:47 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMemberLevelId() == null) ? 0 : getMemberLevelId().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getNickname() == null) ? 0 : getNickname().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getIcon() == null) ? 0 : getIcon().hashCode());
        result = prime * result + ((getGender() == null) ? 0 : getGender().hashCode());
        result = prime * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getJob() == null) ? 0 : getJob().hashCode());
        result = prime * result + ((getPersonalizedSignature() == null) ? 0 : getPersonalizedSignature().hashCode());
        result = prime * result + ((getSourceType() == null) ? 0 : getSourceType().hashCode());
        result = prime * result + ((getIntegration() == null) ? 0 : getIntegration().hashCode());
        result = prime * result + ((getGrowth() == null) ? 0 : getGrowth().hashCode());
        result = prime * result + ((getLuckeyCount() == null) ? 0 : getLuckeyCount().hashCode());
        result = prime * result + ((getHistoryIntegration() == null) ? 0 : getHistoryIntegration().hashCode());
        return result;
    }
}