package com.ac.gmall.manage.mapper;

import entity.PmsBaseCatelog2;
import entity.PmsBaseCatelog2Criteria;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface PmsBaseCatelog2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    int countByExample(PmsBaseCatelog2Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    int deleteByExample(PmsBaseCatelog2Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    int insert(PmsBaseCatelog2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    int insertSelective(PmsBaseCatelog2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    List<PmsBaseCatelog2> selectByExampleWithRowbounds(PmsBaseCatelog2Criteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    List<PmsBaseCatelog2> selectByExample(PmsBaseCatelog2Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    PmsBaseCatelog2 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    int updateByExampleSelective(@Param("record") PmsBaseCatelog2 record, @Param("example") PmsBaseCatelog2Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    int updateByExample(@Param("record") PmsBaseCatelog2 record, @Param("example") PmsBaseCatelog2Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    int updateByPrimaryKeySelective(PmsBaseCatelog2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    int updateByPrimaryKey(PmsBaseCatelog2 record);
}