package com.ac.gmall.manage.mapper;

import entity.PmsBaseSaleAttr;
import entity.PmsBaseSaleAttrCriteria;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface PmsBaseSaleAttrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_sale_attr
     *
     * @mbggenerated Wed Dec 04 14:44:38 CST 2019
     */
    int countByExample(PmsBaseSaleAttrCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_sale_attr
     *
     * @mbggenerated Wed Dec 04 14:44:38 CST 2019
     */
    int deleteByExample(PmsBaseSaleAttrCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_sale_attr
     *
     * @mbggenerated Wed Dec 04 14:44:38 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_sale_attr
     *
     * @mbggenerated Wed Dec 04 14:44:38 CST 2019
     */
    int insert(PmsBaseSaleAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_sale_attr
     *
     * @mbggenerated Wed Dec 04 14:44:38 CST 2019
     */
    int insertSelective(PmsBaseSaleAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_sale_attr
     *
     * @mbggenerated Wed Dec 04 14:44:38 CST 2019
     */
    List<PmsBaseSaleAttr> selectByExampleWithRowbounds(PmsBaseSaleAttrCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_sale_attr
     *
     * @mbggenerated Wed Dec 04 14:44:38 CST 2019
     */
    List<PmsBaseSaleAttr> selectByExample(PmsBaseSaleAttrCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_sale_attr
     *
     * @mbggenerated Wed Dec 04 14:44:38 CST 2019
     */
    PmsBaseSaleAttr selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_sale_attr
     *
     * @mbggenerated Wed Dec 04 14:44:38 CST 2019
     */
    int updateByExampleSelective(@Param("record") PmsBaseSaleAttr record, @Param("example") PmsBaseSaleAttrCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_sale_attr
     *
     * @mbggenerated Wed Dec 04 14:44:38 CST 2019
     */
    int updateByExample(@Param("record") PmsBaseSaleAttr record, @Param("example") PmsBaseSaleAttrCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_sale_attr
     *
     * @mbggenerated Wed Dec 04 14:44:38 CST 2019
     */
    int updateByPrimaryKeySelective(PmsBaseSaleAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_sale_attr
     *
     * @mbggenerated Wed Dec 04 14:44:38 CST 2019
     */
    int updateByPrimaryKey(PmsBaseSaleAttr record);
}