package com.ac.gmall.manage.mapper;

import entity.PmsBaseCatelog1;
import entity.PmsBaseCatelog1Criteria;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface PmsBaseCatelog1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog1
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    int countByExample(PmsBaseCatelog1Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog1
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    int deleteByExample(PmsBaseCatelog1Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog1
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog1
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    int insert(PmsBaseCatelog1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog1
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    int insertSelective(PmsBaseCatelog1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog1
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    List<PmsBaseCatelog1> selectByExampleWithRowbounds(PmsBaseCatelog1Criteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog1
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    List<PmsBaseCatelog1> selectByExample(PmsBaseCatelog1Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog1
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    PmsBaseCatelog1 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog1
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    int updateByExampleSelective(@Param("record") PmsBaseCatelog1 record, @Param("example") PmsBaseCatelog1Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog1
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    int updateByExample(@Param("record") PmsBaseCatelog1 record, @Param("example") PmsBaseCatelog1Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog1
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    int updateByPrimaryKeySelective(PmsBaseCatelog1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog1
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    int updateByPrimaryKey(PmsBaseCatelog1 record);
}