package com.ac.gmall.manage.mapper;

import entity.PmsBaseAttrInfo;
import entity.PmsBaseAttrInfoCriteria;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface PmsBaseAttrInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    int countByExample(PmsBaseAttrInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    int deleteByExample(PmsBaseAttrInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    int insert(PmsBaseAttrInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    int insertSelective(PmsBaseAttrInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    List<PmsBaseAttrInfo> selectByExampleWithRowbounds(PmsBaseAttrInfoCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    List<PmsBaseAttrInfo> selectByExample(PmsBaseAttrInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    PmsBaseAttrInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    int updateByExampleSelective(@Param("record") PmsBaseAttrInfo record, @Param("example") PmsBaseAttrInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    int updateByExample(@Param("record") PmsBaseAttrInfo record, @Param("example") PmsBaseAttrInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    int updateByPrimaryKeySelective(PmsBaseAttrInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    int updateByPrimaryKey(PmsBaseAttrInfo record);
}