package com.ac.gmall.manage.mapper;

import entity.PmsBaseAttrValue;
import entity.PmsBaseAttrValueCriteria;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface PmsBaseAttrValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_value
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    int countByExample(PmsBaseAttrValueCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_value
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    int deleteByExample(PmsBaseAttrValueCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_value
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_value
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    int insert(PmsBaseAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_value
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    int insertSelective(PmsBaseAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_value
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    List<PmsBaseAttrValue> selectByExampleWithRowbounds(PmsBaseAttrValueCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_value
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    List<PmsBaseAttrValue> selectByExample(PmsBaseAttrValueCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_value
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    PmsBaseAttrValue selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_value
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    int updateByExampleSelective(@Param("record") PmsBaseAttrValue record, @Param("example") PmsBaseAttrValueCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_value
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    int updateByExample(@Param("record") PmsBaseAttrValue record, @Param("example") PmsBaseAttrValueCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_value
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    int updateByPrimaryKeySelective(PmsBaseAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_value
     *
     * @mbggenerated Tue Dec 03 12:21:30 CST 2019
     */
    int updateByPrimaryKey(PmsBaseAttrValue record);
}