package com.ac.gmall.manage.mapper;

import entity.PmsBaseCatelog3;
import entity.PmsBaseCatelog3Criteria;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface PmsBaseCatelog3Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog3
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    int countByExample(PmsBaseCatelog3Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog3
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    int deleteByExample(PmsBaseCatelog3Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog3
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog3
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    int insert(PmsBaseCatelog3 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog3
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    int insertSelective(PmsBaseCatelog3 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog3
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    List<PmsBaseCatelog3> selectByExampleWithRowbounds(PmsBaseCatelog3Criteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog3
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    List<PmsBaseCatelog3> selectByExample(PmsBaseCatelog3Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog3
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    PmsBaseCatelog3 selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog3
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    int updateByExampleSelective(@Param("record") PmsBaseCatelog3 record, @Param("example") PmsBaseCatelog3Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog3
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    int updateByExample(@Param("record") PmsBaseCatelog3 record, @Param("example") PmsBaseCatelog3Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog3
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    int updateByPrimaryKeySelective(PmsBaseCatelog3 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog3
     *
     * @mbggenerated Mon Dec 02 13:23:40 CST 2019
     */
    int updateByPrimaryKey(PmsBaseCatelog3 record);
}