package com.ac.gmall.manage.mapper;

import entity.PmsProductInfo;
import entity.PmsProductInfoCriteria;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface PmsProductInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    int countByExample(PmsProductInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    int deleteByExample(PmsProductInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    int insert(PmsProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    int insertSelective(PmsProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    List<PmsProductInfo> selectByExampleWithRowbounds(PmsProductInfoCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    List<PmsProductInfo> selectByExample(PmsProductInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    PmsProductInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    int updateByExampleSelective(@Param("record") PmsProductInfo record, @Param("example") PmsProductInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    int updateByExample(@Param("record") PmsProductInfo record, @Param("example") PmsProductInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    int updateByPrimaryKeySelective(PmsProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    int updateByPrimaryKey(PmsProductInfo record);
}