package com.ac.gmall.manage.mapper;

import entity.PmsProductSaleAttrValue;
import entity.PmsProductSaleAttrValueCriteria;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface PmsProductSaleAttrValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr_value
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    int countByExample(PmsProductSaleAttrValueCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr_value
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    int deleteByExample(PmsProductSaleAttrValueCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr_value
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr_value
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    int insert(PmsProductSaleAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr_value
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    int insertSelective(PmsProductSaleAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr_value
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    List<PmsProductSaleAttrValue> selectByExampleWithRowbounds(PmsProductSaleAttrValueCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr_value
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    List<PmsProductSaleAttrValue> selectByExample(PmsProductSaleAttrValueCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr_value
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    PmsProductSaleAttrValue selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr_value
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    int updateByExampleSelective(@Param("record") PmsProductSaleAttrValue record, @Param("example") PmsProductSaleAttrValueCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr_value
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    int updateByExample(@Param("record") PmsProductSaleAttrValue record, @Param("example") PmsProductSaleAttrValueCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr_value
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    int updateByPrimaryKeySelective(PmsProductSaleAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr_value
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    int updateByPrimaryKey(PmsProductSaleAttrValue record);
}