package com.ac.gmall.manage.mapper;

import entity.PmsProductSaleAttr;
import entity.PmsProductSaleAttrCriteria;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface PmsProductSaleAttrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    int countByExample(PmsProductSaleAttrCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    int deleteByExample(PmsProductSaleAttrCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    int insert(PmsProductSaleAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    int insertSelective(PmsProductSaleAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    List<PmsProductSaleAttr> selectByExampleWithRowbounds(PmsProductSaleAttrCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    List<PmsProductSaleAttr> selectByExample(PmsProductSaleAttrCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    PmsProductSaleAttr selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    int updateByExampleSelective(@Param("record") PmsProductSaleAttr record, @Param("example") PmsProductSaleAttrCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    int updateByExample(@Param("record") PmsProductSaleAttr record, @Param("example") PmsProductSaleAttrCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    int updateByPrimaryKeySelective(PmsProductSaleAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbggenerated Wed Dec 04 13:33:25 CST 2019
     */
    int updateByPrimaryKey(PmsProductSaleAttr record);
}