package com.ac.gmall.user.mapper;

import java.util.List;

import entity.UserMember;
import entity.UserMemberCriteria;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface UserMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     *
     * @mbggenerated Fri Nov 22 13:31:21 CST 2019
     */
    int countByExample(UserMemberCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     *
     * @mbggenerated Fri Nov 22 13:31:21 CST 2019
     */
    int deleteByExample(UserMemberCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     *
     * @mbggenerated Fri Nov 22 13:31:21 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     *
     * @mbggenerated Fri Nov 22 13:31:21 CST 2019
     */
    int insert(UserMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     *
     * @mbggenerated Fri Nov 22 13:31:21 CST 2019
     */
    int insertSelective(UserMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     *
     * @mbggenerated Fri Nov 22 13:31:21 CST 2019
     */
    List<UserMember> selectByExampleWithRowbounds(UserMemberCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     *
     * @mbggenerated Fri Nov 22 13:31:21 CST 2019
     */
    List<UserMember> selectByExample(UserMemberCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     *
     * @mbggenerated Fri Nov 22 13:31:21 CST 2019
     */
    UserMember selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     *
     * @mbggenerated Fri Nov 22 13:31:21 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserMember record, @Param("example") UserMemberCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     *
     * @mbggenerated Fri Nov 22 13:31:21 CST 2019
     */
    int updateByExample(@Param("record") UserMember record, @Param("example") UserMemberCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     *
     * @mbggenerated Fri Nov 22 13:31:21 CST 2019
     */
    int updateByPrimaryKeySelective(UserMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     *
     * @mbggenerated Fri Nov 22 13:31:21 CST 2019
     */
    int updateByPrimaryKey(UserMember record);
}