server:
  port: 8071
spring:
  datasource:
    druid:
      username: gmail
      password: 4321`qaz
      url: jdbc:mysql://localhost:3306/gmail?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  dubbo:
    application: manage-service #dubbo中的服务名称
    protocol:
      name: dubbo #dubbo中的通信协议名称
    registry:
      address: 192.168.211.51:2181 #zookeeper注册中线地址
      protocol: zookeeper #zookeeper通信协议名称
    base-package: com.ac.gmall #dubbo服务的扫描路径

mybatis:
  type-aliases-package: entity
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    cache-enabled: true # 在本项目之中开启二级缓存
logging:
  level: info